### ISSUE TITLE
ant build-unit fails

### ISSUE THREAD

**Issue by abinder-1** [shopwareLabs/shopware-vagrant#61]
I am following the official developers guide: https://developers.shopware.com/developers-guide/vagrant-phpstorm/

When it comes to the step **"Build Shopware"** and the substep **"2. Configure your build properties"** I get the following error message.

`Unable to locate tools.jar. Expected to find it in /usr/lib/jvm/java-8-openjdk-amd64/lib/tools.jar`

```
vagrant@shopware:~/www/shopware/build$ ant configure
Unable to locate tools.jar. Expected to find it in /usr/lib/jvm/java-8-openjdk-amd64/lib/tools.jar
Buildfile: /home/vagrant/www/shopware/build/build.xml

configure:
    [input] Please enter db-host: [localhost]
localhost
    [input] Please enter db-port: [3306]
3306
    [input] Please enter db-name: []
shopware
    [input] Please enter db-username: []
root
    [input] Please enter db-password:
shopware
    [input] Please enter app.host (Hostname e.g. example.com): []
192.168.33.10
    [input] Please enter app.path (e.g. /shopware. Leave blank if installed in document root): []
/shopware

write-properties:
[propertyfile] Creating new property file: /home/vagrant/www/shopware/build/build.properties

BUILD SUCCESSFUL
Total time: 42 seconds
vagrant@shopware:~/www/shopware/build$ ant build-unit
Unable to locate tools.jar. Expected to find it in /usr/lib/jvm/java-8-openjdk-amd64/lib/tools.jar
Buildfile: /home/vagrant/www/shopware/build/build.xml

check-composer-binary:

install-composer-binary:
     [exec] All settings correct for using Composer
     [exec] Downloading...
     [exec]
     [exec] Composer (version 1.9.2) successfully installed to: /home/vagrant/www/shopware/composer.phar
     [exec] Use it: php composer.phar
     [exec]

update-composer-binary:
     [exec] You are already using composer version 1.9.2 (stable channel).

build-composer-install:
     [exec] Loading composer repositories with package information
     [exec] Installing dependencies (including require-dev) from lock file
     [exec] Package operations: 148 installs, 0 updates, 0 removals
     [exec]
     [exec] Fatal error: Uncaught TypeError: Return value of PackageVersions\Installer::activate() must be an instance of PackageVersions\void, none returned i                                   n /home/vagrant/www/shopware/vendor/ocramius/package-versions/src/PackageVersions/Installer.php:80
     [exec] Stack trace:
     [exec] #0 phar:///home/vagrant/www/shopware/composer.phar/src/Composer/Plugin/PluginManager.php(237): PackageVersions\Installer->activate(Object(Composer\                                   Composer), Object(Composer\IO\ConsoleIO))
     [exec] #1 phar:///home/vagrant/www/shopware/composer.phar/src/Composer/Plugin/PluginManager.php(206): Composer\Plugin\PluginManager->addPlugin(Object(Pack                                   ageVersions\Installer))
     [exec] #2 phar:///home/vagrant/www/shopware/composer.phar/src/Composer/Installer/PluginInstaller.php(62): Composer\Plugin\PluginManager->registerPackage(O                                   bject(Composer\Package\CompletePackage), true)
     [exec] #3 phar:///home/vagrant/www/shopware/composer.phar/src/Composer/Installer/InstallationManager.php(173): Composer\Installer\PluginInstaller->install                                   (Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\P in /home/vagrant/www/shopware/vendor/ocramius/package-versions/src/PackageVersion                                   s/Installer.php on line 80
     [exec]   - Installing ocramius/package-versions (1.4.2): Downloading (100%)
     [exec] PHP Fatal error:  Uncaught TypeError: Return value of PackageVersions\Installer::activate() must be an instance of PackageVersions\void, none retur                                   ned in /home/vagrant/www/shopware/vendor/ocramius/package-versions/src/PackageVersions/Installer.php:80
     [exec] Stack trace:
     [exec] #0 phar:///home/vagrant/www/shopware/composer.phar/src/Composer/Plugin/PluginManager.php(237): PackageVersions\Installer->activate(Object(Composer\                                   Composer), Object(Composer\IO\ConsoleIO))
     [exec] #1 phar:///home/vagrant/www/shopware/composer.phar/src/Composer/Plugin/PluginManager.php(206): Composer\Plugin\PluginManager->addPlugin(Object(Pack                                   ageVersions\Installer))
     [exec] #2 phar:///home/vagrant/www/shopware/composer.phar/src/Composer/Installer/PluginInstaller.php(62): Composer\Plugin\PluginManager->registerPackage(O                                   bject(Composer\Package\CompletePackage), true)
     [exec] #3 phar:///home/vagrant/www/shopware/composer.phar/src/Composer/Installer/InstallationManager.php(173): Composer\Installer\PluginInstaller->install                                   (Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\P in /home/vagrant/www/shopware/vendor/ocramius/package-versions/src/PackageVersion                                   s/Installer.php on line 80

BUILD FAILED
/home/vagrant/www/shopware/build/build.xml:98: exec returned: 255

Total time: 2 seconds
```

**Comment by abinder-1** [comment]
This problem can be solved by installing the openjdk-8-**jdk**.

`sudo apt-get update && sudo apt-get install openjdk-8-jdk`

But after that the Build-Log-Output changes to:

```
vagrant@shopware:~/www/shopware/build$ ant build-unit
Buildfile: /home/vagrant/www/shopware/build/build.xml

check-composer-binary:

install-composer-binary:

update-composer-binary:
     [exec] You are already using composer version 1.9.2 (stable channel).

build-composer-install:
     [exec]
     [exec] Fatal error: Uncaught TypeError: Return value of PackageVersions\Installer::activate() must be an instance of PackageVersions\void, none returned in /home/vagrant/www/shopware/vendor/ocramius/package-versions/src/PackageVersions/Installer.php:80
     [exec] Stack trace:
     [exec] #0 phar:///home/vagrant/www/shopware/composer.phar/src/Composer/Plugin/PluginManager.php(237): PackageVersions\Installer->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
     [exec] #1 phar:///home/vagrant/www/shopware/composer.phar/src/Composer/Plugin/PluginManager.php(206): Composer\Plugin\PluginManager->addPlugin(Object(PackageVersions\Installer))
     [exec] #2 phar:///home/vagrant/www/shopware/composer.phar/src/Composer/Installer/PluginInstaller.php(62): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage), true)
     [exec] #3 phar:///home/vagrant/www/shopware/composer.phar/src/Composer/Installer/InstallationManager.php(173): Composer\Installer\PluginInstaller->install(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\P in /home/vagrant/www/shopware/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 80
     [exec] Loading composer repositories with package information
     [exec] Installing dependencies (including require-dev) from lock file
     [exec] Package operations: 148 installs, 0 updates, 0 removals
     [exec]   - Installing ocramius/package-versions (1.4.2): Loading from cache
     [exec] PHP Fatal error:  Uncaught TypeError: Return value of PackageVersions\Installer::activate() must be an instance of PackageVersions\void, none returned in /home/vagrant/www/shopware/vendor/ocramius/package-versions/src/PackageVersions/Installer.php:80
     [exec] Stack trace:
     [exec] #0 phar:///home/vagrant/www/shopware/composer.phar/src/Composer/Plugin/PluginManager.php(237): PackageVersions\Installer->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
     [exec] #1 phar:///home/vagrant/www/shopware/composer.phar/src/Composer/Plugin/PluginManager.php(206): Composer\Plugin\PluginManager->addPlugin(Object(PackageVersions\Installer))
     [exec] #2 phar:///home/vagrant/www/shopware/composer.phar/src/Composer/Installer/PluginInstaller.php(62): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage), true)
     [exec] #3 phar:///home/vagrant/www/shopware/composer.phar/src/Composer/Installer/InstallationManager.php(173): Composer\Installer\PluginInstaller->install(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\P in /home/vagrant/www/shopware/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 80

BUILD FAILED
/home/vagrant/www/shopware/build/build.xml:98: exec returned: 255

```

**Comment by shyim** [comment]
Change your PHP Version to 7.2. Then it should work

**Comment by abinder-1** [comment]
This problem can be solved by changing the PHP Version (VM default is 7.0) by executing `changephp_7.2` and after that (as proposed) ` service apache2 restart`

**Comment by abinder-1** [comment]
Now I have a permission problem: 

```
vagrant@shopware:~/www/shopware/build$ ant build-unit
Buildfile: /home/vagrant/www/shopware/build/build.xml

check-composer-binary:

install-composer-binary:

update-composer-binary:
     [exec] You are already using composer version 1.9.2 (stable channel).

build-composer-install:
     [exec] Loading composer repositories with package information
     [exec] Installing dependencies (including require-dev) from lock file
     [exec] Package operations: 148 installs, 0 updates, 0 removals
     [exec]   - Installing ocramius/package-versions (1.4.2): Loading from cache
     [exec]   - Installing bcremer/line-reader (0.2.0): Downloading (100%)
     [exec]   - Installing beberlei/assert (v2.9.9): Downloading (100%)
     [exec]   - Installing beberlei/doctrineextensions (v1.2.1): Downloading (100%)
     [exec]   - Installing cocur/slugify (v3.1): Downloading (100%)
     [exec]   - Installing doctrine/inflector (1.3.1): Downloading (100%)
     [exec]   - Installing symfony/polyfill-mbstring (v1.13.1): Downloading (100%)
     [exec]   - Installing psr/log (1.1.2): Downloading (100%)
     [exec]   - Installing symfony/debug (v4.4.2): Downloading (100%)
     [exec]   - Installing symfony/console (v3.4.36): Downloading (100%)
     [exec]   - Installing doctrine/instantiator (1.3.0): Downloading (100%)
     [exec]   - Installing doctrine/lexer (1.2.0): Downloading (100%)
     [exec]   - Installing doctrine/annotations (v1.8.0): Downloading (100%)
     [exec]   - Installing doctrine/reflection (v1.0.0): Downloading (100%)
     [exec]   - Installing doctrine/event-manager (1.1.0): Downloading (100%)
     [exec]   - Installing doctrine/collections (v1.6.2): Downloading (100%)
     [exec]   - Installing doctrine/cache (v1.8.0): Downloading (100%)
     [exec]   - Installing doctrine/persistence (1.2.0): Downloading (100%)
     [exec]   - Installing doctrine/common (v2.11.0): Downloading (100%)
     [exec]   - Installing doctrine/dbal (v2.6.3): Downloading (100%)
     [exec]   - Installing doctrine/orm (v2.6.4): Downloading (100%)
     [exec]   - Installing egulias/email-validator (1.2.14): Downloading (100%)
     [exec]   - Installing react/promise (v2.7.1): Downloading (100%)
     [exec]   - Installing guzzlehttp/streams (3.0.0): Downloading (100%)
     [exec]   - Installing guzzlehttp/ringphp (1.1.1): Downloading (100%)
     [exec]   - Installing elasticsearch/elasticsearch (v6.7.1): Downloading (100%)
     [exec]   - Installing firebase/php-jwt (v5.0.0): Downloading (100%)
     [exec]   - Installing grpc/grpc (1.26.1): Downloading (100%)
     [exec]   - Installing google/protobuf (v3.5.2): Downloading (100%)
     [exec]   - Installing psr/http-message (1.0.1): Downloading (100%)
     [exec]   - Installing psr/cache (1.0.1): Downloading (100%)
     [exec]   - Installing guzzlehttp/psr7 (1.4.2): Downloading (100%)
     [exec]   - Installing guzzlehttp/guzzle (5.3.3): Downloading (100%)
     [exec]   - Installing google/auth (v1.6.1): Downloading (100%)
     [exec]   - Installing google/gax (0.29.1): Downloading (100%)
     [exec]   - Installing google/proto-client (0.29.0): Downloading (100%)
     [exec]   - Installing guzzlehttp/promises (v1.3.1): Downloading (100%)
     [exec]   - Installing league/flysystem (1.0.46): Downloading (100%)
     [exec]   - Installing mtdowling/jmespath.php (2.4.0): Downloading (100%)
     [exec]   - Installing aws/aws-sdk-php (3.130.2): Downloading (100%)
     [exec]   - Installing league/flysystem-aws-s3-v3 (1.0.19): Downloading (100%)
     [exec]   - Installing monolog/monolog (1.23.0): Downloading (100%)
     [exec]   - Installing setasign/fpdi (1.6.2): Downloading (100%)
     [exec]   - Installing paragonie/random_compat (v2.0.18): Downloading (100%)
     [exec]   - Installing myclabs/deep-copy (1.9.4): Downloading (100%)
     [exec]   - Installing mpdf/mpdf (v7.1.9): Downloading (100%)
     [exec]   - Installing symfony/polyfill-ctype (v1.13.1): Downloading (100%)
     [exec]   - Installing symfony/serializer (v3.4.36): Downloading (100%)
     [exec]   - Installing ongr/elasticsearch-dsl (v6.0.3): Downloading (100%)
     [exec]   - Installing oyejorge/less.php (v1.7.0.14): Downloading (100%)
     [exec]   - Installing php-http/message-factory (v1.0.2): Downloading (100%)
     [exec]   - Installing clue/stream-filter (v1.4.1): Downloading (100%)
     [exec]   - Installing php-http/message (1.6.0): Downloading (100%)
     [exec]   - Installing php-http/promise (v1.0.0): Downloading (100%)
     [exec]   - Installing php-http/httplug (v1.1.0): Downloading (100%)
     [exec]   - Installing php-http/discovery (1.7.3): Downloading (100%)
     [exec]   - Installing php-http/curl-client (v1.7.1): Downloading (100%)
     [exec]   - Installing ramsey/uuid (3.5.2): Downloading (100%)
     [exec]   - Installing rize/uri-template (0.3.2): Downloading (100%)
     [exec]   - Installing setasign/fpdf (1.8.1): Downloading (100%)
     [exec]   - Installing stecman/symfony-console-completion (0.10.1): Downloading (100%)
     [exec]   - Installing google/cloud (v0.49.0): Downloading (100%)
     [exec]   - Installing superbalist/flysystem-google-storage (6.0.0): Downloading (100%)
     [exec]   - Installing symfony/cache-contracts (v1.1.7): Downloading (100%)
     [exec]   - Installing symfony/class-loader (v3.4.36): Downloading (100%)
     [exec]   - Installing symfony/filesystem (v3.4.36): Downloading (100%)
     [exec]   - Installing symfony/config (v3.4.36): Downloading (100%)
     [exec]   - Installing psr/container (1.0.0): Downloading (100%)
     [exec]   - Installing symfony/dependency-injection (v3.4.36): Downloading (100%)
     [exec]   - Installing symfony/event-dispatcher-contracts (v1.1.7): Downloading (100%)
     [exec]   - Installing symfony/var-exporter (v4.4.2): Downloading (100%)
     [exec]   - Installing symfony/service-contracts (v1.1.8): Downloading (100%)
     [exec]   - Installing symfony/cache (v4.3.9): Downloading (100%)
     [exec]   - Installing symfony/expression-language (v3.4.36): Downloading (100%)
     [exec]   - Installing symfony/inflector (v4.4.2): Downloading (100%)
     [exec]   - Installing symfony/property-access (v4.4.2): Downloading (100%)
     [exec]   - Installing symfony/options-resolver (v3.4.36): Downloading (100%)
     [exec]   - Installing symfony/intl (v4.4.2): Downloading (100%)
     [exec]   - Installing symfony/polyfill-intl-icu (v1.13.1): Downloading (100%)
     [exec]   - Installing symfony/event-dispatcher (v4.4.2): Downloading (100%)
     [exec]   - Installing symfony/form (v3.4.36): Downloading (100%)
     [exec]   - Installing symfony/polyfill-util (v1.13.1): Downloading (100%)
     [exec]   - Installing symfony/polyfill-php56 (v1.13.1): Downloading (100%)
     [exec]   - Installing symfony/polyfill-php70 (v1.13.1): Downloading (100%)
     [exec]   - Installing symfony/http-foundation (v3.4.36): Downloading (100%)
     [exec]   - Installing symfony/http-kernel (v3.4.36): Downloading (100%)
     [exec]   - Installing symfony/process (v3.4.36): Downloading (100%)
     [exec]   - Installing symfony/translation (v3.4.36): Downloading (100%)
     [exec]   - Installing symfony/validator (v3.4.36): Downloading (100%)
     [exec]   - Installing psr/link (1.0.0): Downloading (100%)
     [exec]   - Installing fig/link-util (1.0.0): Downloading (100%)
     [exec]   - Installing symfony/web-link (v3.4.36): Downloading (100%)
     [exec]   - Installing zendframework/zend-eventmanager (3.2.1): Downloading (100%)
     [exec]   - Installing zendframework/zend-code (3.4.1): Downloading (100%)
     [exec]   - Installing zendframework/zend-escaper (2.5.2): Downloading (100%)
     [exec]   - Installing behat/gherkin (v4.6.0): Downloading (100%)
     [exec]   - Installing symfony/dom-crawler (v2.8.52): Downloading (100%)
     [exec]   - Installing symfony/css-selector (v2.8.52): Downloading (100%)
     [exec]   - Installing symfony/browser-kit (v2.8.52): Downloading (100%)
     [exec]   - Installing fabpot/goutte (v2.0.4): Downloading (100%)
     [exec]   - Installing behat/mink (v1.7.1): Downloading (100%)
     [exec]   - Installing behat/mink-browserkit-driver (1.3.3): Downloading (100%)
     [exec]   - Installing behat/mink-goutte-driver (v1.2.1): Downloading (100%)
     [exec]   - Installing instaclick/php-webdriver (1.4.6): Downloading (100%)
     [exec]   - Installing behat/mink-selenium2-driver (v1.3.1): Downloading (100%)
     [exec]   - Installing behat/transliterator (v1.2.0): Downloading (100%)
     [exec]   - Installing composer/semver (1.5.0): Downloading (100%)
     [exec]   - Installing composer/xdebug-handler (1.4.0): Downloading (100%)
     [exec]   - Installing container-interop/container-interop (1.2.0): Downloading (100%)
     [exec]   - Installing jakub-onderka/php-var-dump-check (v0.3): Downloading (100%)
     [exec]   - Installing symfony/finder (v3.4.36): Downloading (100%)
     [exec]   - Installing symfony/stopwatch (v4.4.2): Downloading (100%)
     [exec]   - Installing symfony/polyfill-php72 (v1.13.1): Downloading (100%)
     [exec]   - Installing php-cs-fixer/diff (v1.3.0): Downloading (100%)
     [exec]   - Installing friendsofphp/php-cs-fixer (v2.16.1): Downloading (100%)
     [exec]   - Installing kubawerlos/php-cs-fixer-custom-fixers (v1.17.0): Downloading (100%)
     [exec]   - Installing webmozart/assert (1.6.0): Downloading (100%)
     [exec]   - Installing phpdocumentor/reflection-common (2.0.0): Downloading (100%)
     [exec]   - Installing phpdocumentor/type-resolver (1.0.1): Downloading (100%)
     [exec]   - Installing phpdocumentor/reflection-docblock (4.3.4): Downloading (100%)
     [exec]   - Installing nikic/php-parser (v4.3.0): Downloading (100%)
     [exec]   - Installing phpstan/phpstan (0.12.3): Downloading (100%)
     [exec]   - Installing phpunit/php-token-stream (3.1.1): Downloading (100%)
     [exec]   - Installing sebastian/version (2.0.1): Downloading (100%)
     [exec]   - Installing sebastian/resource-operations (2.0.1): Downloading (100%)
     [exec]   - Installing sebastian/recursion-context (3.0.0): Downloading (100%)
     [exec]   - Installing sebastian/object-reflector (1.1.1): Downloading (100%)
     [exec]   - Installing sebastian/object-enumerator (3.0.3): Downloading (100%)
     [exec]   - Installing sebastian/global-state (2.0.0): Downloading (100%)
     [exec]   - Installing sebastian/exporter (3.1.2): Downloading (100%)
     [exec]   - Installing sebastian/environment (4.2.3): Downloading (100%)
     [exec]   - Installing sebastian/diff (3.0.2): Downloading (100%)
     [exec]   - Installing sebastian/comparator (3.0.2): Downloading (100%)
     [exec]   - Installing phpunit/php-timer (2.1.2): Downloading (100%)
     [exec]   - Installing phpunit/php-text-template (1.2.1): Downloading (100%)
     [exec]   - Installing phpunit/php-file-iterator (2.0.2): Downloading (100%)
     [exec]   - Installing theseer/tokenizer (1.1.3): Downloading (100%)
     [exec]   - Installing sebastian/code-unit-reverse-lookup (1.0.1): Downloading (100%)
     [exec]   - Installing phpunit/php-code-coverage (6.1.4): Downloading (100%)
     [exec]   - Installing phpspec/prophecy (1.10.1): Downloading (100%)
     [exec]   - Installing phar-io/version (2.0.1): Downloading (100%)
     [exec]   - Installing phar-io/manifest (1.0.3): Downloading (100%)
     [exec]   - Installing phpunit/phpunit (7.5.18): Downloading (100%)
     [exec]   - Installing ocramius/proxy-manager (2.2.2): Downloading (100%)
     [exec]   - Installing symfony/yaml (v3.4.22): Downloading (100%)
     [exec]   - Installing behat/behat (v3.5.0): Downloading (100%)
     [exec]   - Installing behat/mink-extension (v2.2): Downloading (100%)
     [exec]   - Installing sensiolabs/behat-page-object-extension (v2.1.0): Downloading (100%)
     [exec] Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
     [exec] Generating optimized autoload files
     [exec] Warning: Ambiguous class resolution, "Doctrine\ORM\Persisters\Entity\BasicEntityPersister" was found in both "$baseDir . '/engine/Library/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php" and "/home/vagrant/www/shopware/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php", the first will be used.
     [exec] Warning: Ambiguous class resolution, "Doctrine\Common\Proxy\AbstractProxyFactory" was found in both "$baseDir . '/engine/Library/Doctrine/Common/Proxy/AbstractProxyFactory.php" and "/home/vagrant/www/shopware/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php", the first will be used.
     [exec] ocramius/package-versions:  Generating version class...
     [exec] ocramius/package-versions: ...done generating version class
     [exec] > ./build/composer-post-install-cmd.sh
     [exec] sh: 1: ./build/composer-post-install-cmd.sh: Permission denied
     [exec] Script ./build/composer-post-install-cmd.sh handling the post-install-cmd event returned with error code 126

BUILD FAILED
/home/vagrant/www/shopware/build/build.xml:98: exec returned: 126
```

**Comment by abinder-1** [comment]
After that I make the file executable `chmod a+x composer-post-install-cmd.sh` and get a "file not found" error?

```
vagrant@shopware:~/www/shopware/build$ ant build-unit
Buildfile: /home/vagrant/www/shopware/build/build.xml

check-composer-binary:

install-composer-binary:

update-composer-binary:
     [exec] You are already using composer version 1.9.2 (stable channel).

build-composer-install:
     [exec] Loading composer repositories with package information
     [exec] Installing dependencies (including require-dev) from lock file
     [exec] Nothing to install or update
     [exec] Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
     [exec] Generating optimized autoload files
     [exec] Warning: Ambiguous class resolution, "Doctrine\ORM\Persisters\Entity\BasicEntityPersister" was found in both "$baseDir . '/engine/Library/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php" and "/home/vagrant/www/shopware/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php", the first will be used.
     [exec] Warning: Ambiguous class resolution, "Doctrine\Common\Proxy\AbstractProxyFactory" was found in both "$baseDir . '/engine/Library/Doctrine/Common/Proxy/AbstractProxyFactory.php" and "/home/vagrant/www/shopware/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php", the first will be used.
     [exec] ocramius/package-versions:  Generating version class...
     [exec] ocramius/package-versions: ...done generating version class
     [exec] > ./build/composer-post-install-cmd.sh
     [exec] sh: 1: ./build/composer-post-install-cmd.sh: not found
     [exec] Script ./build/composer-post-install-cmd.sh handling the post-install-cmd event returned with error code 127

BUILD FAILED
/home/vagrant/www/shopware/build/build.xml:98: exec returned: 127

Total time: 4 seconds
```

**Comment by shyim** [comment]
This looks like sync permission issues. You have to make them all executeable.

Do you have still issues here?
